ingress:
  name: capz-workshop-ingress
  namespace: capz-workshop-qa
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
  hosts:
  - name: capz-qa.internal.<dns-name>
    paths:
    - path: /?(.*)
      service: ratingsweb-service
      port: 80