ingress:
  name: capz-workshop-ingress
  namespace: capz-workshop-dev
  annotations:
    ingressClass: nginx
    proxyBodySize: "10m"
    enableCors: "true"
    rewriteTarget: /$1
  tls:
  - hosts:
    - "*.internal.<dns-name>"
    secretName: capz-workshop-tls-secret
  hosts:
  - name: capz-dev.internal.<dns-name>
    paths:
    - path: /?(.*)
      pathType: Prefix
      service: ratingsweb-service
      port: 80 
  