ingress:
  name: smoke-ingress
  namespace: smoke
  annotations:
   ingressClass: nginx
   enableCors: "true"
   rewriteTarget: /$1
  tls:
  - hosts:
    - "*.internal.<dns-name>"
    secretName: capz-workshop-tls-secret
  hosts:
  - name: capz-smoke.internal.<dns-name>
    paths:
    - path: /nginx/?(.*)
      pathType: Prefix
      service: nginx-svc
      port: 80
  