apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.developer.roleName }}
  namespace: {{ .Values.developer.roleNamespace }}
rules:
{{ toYaml .Values.developer.rules }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.developer.bindingName }}
  namespace: {{ .Values.developer.bindingNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.developer.roleName }}
subjects:
{{- range $subject := .Values.developer.subjects}}
- name: {{ $subject.name}}
  namespace: {{ $subject.namespace}}
  kind: {{ $subject.kind}}
{{- end }}